name: CI BACK
# TODO: activer le cache

permissions:
  contents: read
on: 
  workflow_call:
  push:
    branches: [ci-tests, main]
    paths:
      - 'back/**'
      - '.github/**'

env:
  JAVA_VERSION: '17' # used in back app
  GRADLE_VERSION: '8.7' # version used in back app

jobs:
  # tests back
  back-tests:
    runs-on: ubuntu-26.04
    steps:
      - name : checkout pour tests back
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1
      - name: install java ${{env.JAVA_VERSION}}
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: ${{env.JAVA_VERSION}}
      - name: configuration gradle ${{env.GRADLE_VERSION}}
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          gradle-version: ${{env.GRADLE_VERSION}}
      - name: back - tests auto 
        run: cd back && chmod +x ./gradlew && ./gradlew test

# lint

# construction

## publier l'image sur github


# déploiement
## manuel
