name: CI front
# TODO: activer le cache

# security : par défaut droit de lecture uniquement ( moindre privilège )
permissions:
  contents: read
on: 
  workflow_dispatch:

env:
  NODE_VERSION: '24' # LTS

# validation
jobs:
  ## tests front
  front-tests:
    runs-on: ubuntu-26.04
    # security : utiliser le hash à la place d'un tag mutable
    steps:
      - name: installation node ${{env.NODE_VERSION}}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{env.NODE_VERSION}}
          # cache: 'npm' # cache entre chaque run 
          # c'est un sous dossier il faut lui préciser le fichier à vérifier pour les caches hit
          # cache-dependency-path: front/package-lock.json
      - name: installation chrome
        uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # v2.1.2
      - name: checkout pour tests front
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1
      - name: front - tests auto + code coverage
        # commandes en une ligne pour gestion du cache
        run: cd front && npm ci && npx ng test --code-coverage --watch=false --browsers=ChromeHeadless
    # front-lint:
    
