name: CI
# TODO: activer le cache

# security : par défaut droit de lecture uniquement ( moindre privilège )
permissions:
  contents: read
on: 
  workflow_dispatch:
    branches: [ci-tests]
  push:
    branches: [main, ci-tests]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '24' # LTS
  JAVA_VERSION: '17' # used in back app
  GRADLE_VERSION: '8.7' # version used in back app

# validation
jobs:
  ## tests front
  front-tests:
    runs-on: ubuntu-26.04
    # security : utiliser le hash à la place d'un tag mutable
    steps:
      - name: checkout pour tests front
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1
      - name: installation node ${{env.NODE_VERSION}}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm' # cache entre chaque run 
      - name: installation chrome
        uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # v2.1.2
      - name: front - tests auto + code coverage
        # commandes en une ligne pour gestion du cache
        run: cd front && npm ci && npx ng test --code-coverage --watch= false
    # front-lint:

  ## tests back
  # back-tests:
  #   runs-on: ubuntu-26.04
  #   # security : utiliser le hash à la place d'un tag mutable
  #   steps:
  #     - name : checkout pour tests back
  #       uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1
  #     - name: install java ${{env.JAVA_VERSION}}
  #       uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
  #       with:
  #         distribution: temurin
  #         java-version: ${{env.JAVA_VERSION}}
  #     - name: configuration gradle ${{env.GRADLE_VERSION}}
  #       # security : verified creator
  #       uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
  #       with:
  #         gradle-version: ${{env.GRADLE_VERSION}}
  #     - name: back - tests auto
  #       run: cd back && chmod +x ./gradlew && ./gradlew test

  # back-lint:

  ## lint



# construction

## publier l'image sur github


# déploiement
## manuel
